[build]
  publish = "view"
  command = "echo 'Static site ready for deployment'"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[functions]
  directory = "netlify/functions/"

[dev]
  command = "python app.py"
  port = 5000